### ISSUE TITLE
Regenerate package-lock.json without relative deps

### ISSUE THREAD

**Issue by chantastic** [workos/remix-authkit-example#6]
Problem
===

`npm run dev` cannot build the application after fresh clone and install.

This is because `package-lock.json` includes a relative path for `@workos-inc/authkit-remix`.

Proposed solution
===

Regenerate the `package-lock.json` or hide it in `.gitignore`.

Error
===

```sh
> remix-authkit-example@0.0.1 dev
> remix dev


 💿  remix dev

 info  building...
✘ [ERROR] Build failed with 4 errors:
app/root.tsx:26:48: ERROR: Could not resolve "@workos-inc/authkit-remix"
app/routes/_index.tsx:6:24: ERROR: Could not resolve "@workos-inc/authkit-remix"
app/routes/account.tsx:5:25: ERROR: Could not resolve "@workos-inc/authkit-remix"
app/routes/callback.ts:1:27: ERROR: Could not resolve "@workos-inc/authkit-remix" [plugin css-bundle-plugin]

    app/root.tsx:24:30:
      24 │ import { cssBundleHref } from '@remix-run/css-bundle';
         ╵                               ~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    node_modules/@remix-run/dev/dist/compiler/plugins/cssBundlePlugin.js:35:12:
      35 │       build.onLoad({
         ╵             ~~~~~~

    at setup (/Users/chan/Code/remix-authkit-example/node_modules/@remix-run/dev/dist/compiler/plugins/cssBundlePlugin.js:35:13)
    at handlePlugins (/Users/chan/Code/remix-authkit-example/node_modules/esbuild/lib/main.js:1279:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


✘ [ERROR] Could not resolve "@workos-inc/authkit-remix"

    app/root.tsx:28:48:
      28 │ ...ithAuth, getSignInUrl, signOut } from '@workos-inc/authkit-remix';
         ╵                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@workos-inc/authkit-remix" as external to exclude it from the bundle, which will remove this error.


✘ [ERROR] Could not resolve "@workos-inc/authkit-remix"

    app/routes/_index.tsx:26:24:
      26 │ import { signOut } from '@workos-inc/authkit-remix';
         ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@workos-inc/authkit-remix" as external to exclude it from the bundle, which will remove this error.


✘ [ERROR] Could not resolve "@workos-inc/authkit-remix"

    app/routes/account.tsx:24:25:
      24 │ import { withAuth } from '@workos-inc/authkit-remix';
         ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@workos-inc/authkit-remix" as external to exclude it from the bundle, which will remove this error.
```

**Comment by PaulAsjes** [comment]
Oops, fixed and removed unused dependencies.
